# Generated by Django 5.1.1 on 2024-10-15 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descripcion',
            new_name='description',
        ),
    ]
